# Docker Aliases - to save huge amounts of time.
alias dk='docker'
alias dkb='docker build'
alias dkc='docker container'
alias dkcls='docker container ls -a'
alias dkcrun='docker container run'
alias dkcstart='docker container start'
alias dkcstop='docker container stop'
alias dkcrm='docker container rm'
alias dki='docker images -a'
alias dkib='docker image build -t'
alias dkirm='docker image rm'
alias dkn='docker network'
alias dknc='docker network create'
alias dkncn='docker network connect'
alias dknl='docker network ls'
alias dknr='docker network rm'
alias dkp='docker ps -a'
alias dkpl='docker pull'
alias dkr='docker run'
alias dkrm='docker rm'
alias dkrmi='docker rmi'
alias dkstart='docker start'
alias dkstop='docker stop'
alias dkp'docker system prune -a'
